['tltypes'] = {
	['name'] = 'Acura TL Type-S',
	['brand'] = 'aston',
	['model'] = 'tltypes',
	['price'] = 24000,
	['category'] = 'aston',
	['categoryLabel'] = 'aston',
	['hash'] = `tltypes`,
	['shop'] = 'luxury',
},
['ast'] = {
	['name'] = '2013 Aston Martin Vanquish',
	['brand'] = 'aston',
	['model'] = 'ast',
	['price'] = 24000,
	['category'] = 'aston',
	['categoryLabel'] = 'aston',
	['hash'] = `ast`,
	['shop'] = 'luxury',
},
['amdbx'] = {
	['name'] = 'Aston Martin DBX Carbon Edition',
	['brand'] = 'aston',
	['model'] = 'amdbx',
	['price'] = 24000,
	['category'] = 'aston',
	['categoryLabel'] = 'aston',
	['hash'] = `amdbx`,
	['shop'] = 'luxury',
},
['aaq4'] = {
	['name'] = '2017 Audi A4 Quattro ABT',
	['brand'] = 'audi',
	['model'] = 'aaq4',
	['price'] = 24000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `aaq4`,
	['shop'] = 'luxury',
},
['q820'] = {
	['name'] = '2020 Audi Q8 50TDI',
	['brand'] = 'audi',
	['model'] = 'q820',
	['price'] = 15000,
	['category'] = 'audi',
	['categoryLabel'] = 'audi',
	['hash'] = `q820`,
	['shop'] = 'luxury',
}