INSERT INTO `vehicle_categories`(`name`, `label`) VALUES
	("aston", "Aston Martin"),
	("audi", "Audi"),
	("bentley","Bentley"),
	("bmw","BMW"),
	("bugatti","Bugatti"),
	("cadillac", "Cadillac"),
	("chevrolet", "Chevrolet"),
	("dodge", "Dodge"),
	("dacia", "Dacia"),
	("ferrari", "Ferrari"),
	("ford","Ford"),
	("honda", "Honda"),
	("italdesign", "Italdesign"),
	("jaguar","Jaguar"),
	("jeep", "Jeep"),
	("koenigsegg", "Koenigsegg"),
	("lamborghini", "Lamborghini"),
	("lexus", "Lexus"),
	("landrover", "Land Rover"),
	("lotus", "Lotus"),
	("quartz", "Quartz"),
	("maserati", "Maserati"),
	("mazda", "Mazda"),
	("mclaren","McLaren"),
	("mercedesbenz", "Mercedes-Benz"),
	("mercedesamg", "Mercedes-AMG"),
	("mitsubishi", "Mitsubishi"),
	("nissan", "Nissan"),
	("porsche","Porsche"),
	("peugeot", "Peugeot"),
	("rangerover","Range Rover"),
	("renault", "Renault"),
	("rollsroyce", "Rolls-Royce"),
	("subaru", "Subaru"),
	("suzuki", "Suzuki"),
	("tesla", "Tesla"),
	("toyota", "Toyota"),
	("volkswagen", "Volkswagen"),
	("volvo", "Volvo"),
	("wmotors", "W-Motors")
;

INSERT INTO `vehicles`(`name`, `model`, `price`, `category`) VALUES
	("Acura TL Type-S", "tltypes", 24000, "aston"),
	("2013 Aston Martin Vanquish", "ast", 24000, "aston"),
	("Aston Martin DBX Carbon Edition", "amdbx", 24000, "aston"),
	("2017 Audi A4 Quattro ABT","aaq4",24000,"audi"),
	("2020 Audi Q8 50TDI","q820",15000,"audi")
;