Citizen.CreateThread(function ()
--        AddTextEntryByHash(Hash, 'Name')
        AddTextEntryByHash(0x0099C4D0, 'Big Gaper MK2')
        AddTextEntryByHash(0x0124F629, 'Annimo MK2')
        AddTextEntryByHash(0x016C3ACB, 'Debadge Primary Housing /w Carbon Cover')
        AddTextEntryByHash(0x022B4D27, 'Annimo')
        AddTextEntryByHash(0x04167833, 'Debadge Carbon Housing /w Primary Cover')
        AddTextEntryByHash(0x05BCFF3D, 'Bay Shore')
        AddTextEntryByHash(0x06035590, 'Pumped Arch MK2')
        AddTextEntryByHash(0x061FC436, 'Secondary Housing /w Primary Cover')
        AddTextEntryByHash(0x06A0C51E, 'Remove Wing')
        AddTextEntryByHash(0x0787516E, 'OEM Plus')
        AddTextEntryByHash(0x083F04F1, 'Street Swine')
        AddTextEntryByHash(0x0892B529, 'Carbon Bullnose')
        AddTextEntryByHash(0x0A4E18C6, 'Street Swine')
        AddTextEntryByHash(0x0CC5BBF4, 'GTK Intercooler')
        AddTextEntryByHash(0x0D1E9EF4, 'Race Splitter')
        AddTextEntryByHash(0x0E679445, 'Sakura Tree')
        AddTextEntryByHash(0x0E6F607B, 'Big Gaper')
        AddTextEntryByHash(0x0EBBFEA7, 'Secondary Cover')
        AddTextEntryByHash(0x0F12408D, 'Sprayed Intercooler')
        AddTextEntryByHash(0x0F2895D5, 'Extended Single Pipe')
        AddTextEntryByHash(0x107DE9CC, 'Crest')
        AddTextEntryByHash(0x10FC0327, 'Carbon Cover')
        AddTextEntryByHash(0x1117CFE9, 'Bay Shore MK2')
        AddTextEntryByHash(0x127517FD, 'Bay Shore MK2')
        AddTextEntryByHash(0x131B1EA4, 'I-Roxanne')
        AddTextEntryByHash(0x141E553E, 'Tide')
        AddTextEntryByHash(0x1490690E, 'Taillight Housing')
        AddTextEntryByHash(0x14996666, 'Crest')
        AddTextEntryByHash(0x15CCA00C, 'FR-Works Wide')
        AddTextEntryByHash(0x16351C74, 'Debadge Carbon Housing')
        AddTextEntryByHash(0x1749B34A, 'Sports Splitter')
        AddTextEntryByHash(0x18EAE9CC, 'Secondary Housing /w Secondary Cover')
        AddTextEntryByHash(0x197EF55D, 'Ducktail')
        AddTextEntryByHash(0x1A1F236C, 'Light Bar')
        AddTextEntryByHash(0x1B374ED2, 'Street Swine + FR-Works')
        AddTextEntryByHash(0x1B82EEE2, 'Street Swine')
        AddTextEntryByHash(0x1CF93176, 'Stubby Blast Pipes')
        AddTextEntryByHash(0x1E3FDFA3, 'Carbon Bullnose MK2')
        AddTextEntryByHash(0x1EB23143, 'Smoothed')
        AddTextEntryByHash(0x1FB132B4, 'OEM Plus + Time Attack Splitter')
        AddTextEntryByHash(0x2021B356, 'Tide')
        AddTextEntryByHash(0x2106E476, 'Monster GTK Intercooler')
        AddTextEntryByHash(0x219D47F1, 'Time Attack Splitter')
        AddTextEntryByHash(0x232DA78A, 'Debadge')
        AddTextEntryByHash(0x2474BF17, 'Fujiwara Drift Car')
        AddTextEntryByHash(0x25CF78A0, 'Street Swine')
        AddTextEntryByHash(0x26318459, 'Primary Housing /w Secondary Cover')
        AddTextEntryByHash(0x26931606, 'Alien')
        AddTextEntryByHash(0x27927184, 'Half Cage')
        AddTextEntryByHash(0x28E0C937, 'COMSOC SDS')
        AddTextEntryByHash(0x29D643B6, 'Carbon Housing /w Carbon Cover')
        AddTextEntryByHash(0x2E64752C, 'Street Swine')
        AddTextEntryByHash(0x2FF9A9A4, 'Generic Arch')
        AddTextEntryByHash(0x3052A2FC, 'Annimo Lip')
        AddTextEntryByHash(0x314E52A2, 'Carbon Housing /w Primary Cover')
        AddTextEntryByHash(0x32AF5CE2, 'Single Blast Pipes')
        AddTextEntryByHash(0x32B78DAE, 'Twin Turbo')
        AddTextEntryByHash(0x32B95BA0, 'Bayshore')
        AddTextEntryByHash(0x3386C83C, 'Debage /w Primary Cover')
        AddTextEntryByHash(0x35815F75, 'Remove Bumper')
        AddTextEntryByHash(0x35D0DED0, 'Alien')
        AddTextEntryByHash(0x375016DB, 'Big Turbo /w Primary Engine Cover')
        AddTextEntryByHash(0x380B7440, 'Remove Fenders')
        AddTextEntryByHash(0x38665FFA, 'Remove Grill + Lights')
        AddTextEntryByHash(0x3867A8C5, 'Primary Housing /w Carbon Cover')
        AddTextEntryByHash(0x39CD7851, 'Curved Splitter')
        AddTextEntryByHash(0x3A416BF8, 'Knobbed Roxanne')
        AddTextEntryByHash(0x3B91E72D, 'Carbon Housing /w Secondary Cover')
        AddTextEntryByHash(0x3C3FC230, 'X-Flow Arch')
        AddTextEntryByHash(0x3D7C061F, 'Bay Shore MK2')
        AddTextEntryByHash(0x3DD017A7, 'Small Diffuser')
        AddTextEntryByHash(0x3E96EB97, 'Tuner MK2')
        AddTextEntryByHash(0x3F32C7EE, 'Pumped Arch')
        AddTextEntryByHash(0x3FEF760C, 'SSA Drift Demo Car')
        AddTextEntryByHash(0x426B4DB6, 'Element')
        AddTextEntryByHash(0x431E0A69, 'Vented Arch')
        AddTextEntryByHash(0x43EBF7DD, 'Carbon Housing')
        AddTextEntryByHash(0x4439D316, 'Carbon Slatted MK2')
        AddTextEntryByHash(0x444A7BC3, 'Moze')
        AddTextEntryByHash(0x44E3B206, 'Big Turbo /w Secondary Engine Cover')
        AddTextEntryByHash(0x45235AAA, '"R" Badge)')
        AddTextEntryByHash(0x4584AD79, 'Annis Intercooler')
        AddTextEntryByHash(0x45B16C91, 'Debage /w Secondary Cover')
        AddTextEntryByHash(0x475F0633, 'Yeet')
        AddTextEntryByHash(0x47D6881A, 'UN Edition (Black)')
        AddTextEntryByHash(0x48838419, 'Element')
        AddTextEntryByHash(0x48964922, 'Debadge Primary Housing')
        AddTextEntryByHash(0x499D3B75, 'Big Turbo')
        AddTextEntryByHash(0x4B9560DB, 'Lipped Arch')
        AddTextEntryByHash(0x4D665E68, 'Bullnose Mk3')
        AddTextEntryByHash(0x514A8E6E, 'Alien MK2')
        AddTextEntryByHash(0x52A91BDF, 'OEM Plus + Time Attack Splitter + Canards')
        AddTextEntryByHash(0x52C19588, 'Debadge Secondary Housing /w Carbon Cover')
        AddTextEntryByHash(0x549C20BD, 'Smoothed Trunk')
        AddTextEntryByHash(0x58322376, 'Doluck')
        AddTextEntryByHash(0x5835D2DB, 'Annis MK2 Intercooler')
        AddTextEntryByHash(0x58591AA3, 'Element MK2')
        AddTextEntryByHash(0x5924A16A, 'Debadge Carbon Housing /w Secondary Cover')
        AddTextEntryByHash(0x59BD2BE7, 'UN Edition (Grey)')
        AddTextEntryByHash(0x5AD4ED9F, 'Debadge Primary Housing /w Primary Cover')
        AddTextEntryByHash(0x5AFA8658, 'Debadge')
        AddTextEntryByHash(0x5B31D26A, 'Giant Diffuser')
        AddTextEntryByHash(0x5BE66007, 'Secondary Engine Cover')
        AddTextEntryByHash(0x5E0C84F8, 'Venture')
        AddTextEntryByHash(0x620C3B8D, 'Zipper')
        AddTextEntryByHash(0x6782BF0A, 'Debadge Secondary Housing /w Secondary Cover')
        AddTextEntryByHash(0x6807B13D, 'Debage /w Carbon Cover')
        AddTextEntryByHash(0x6CE075C7, 'Small Diffuser MK2')
        AddTextEntryByHash(0x6D5C2397, 'Venture MK2')
        AddTextEntryByHash(0x6F71574F, 'UN Edition (White)')
        AddTextEntryByHash(0x72EADD4A, 'Zipper Inverted')
        AddTextEntryByHash(0x766D5CDF, 'Debadge Secondary Housing /w Primary Cover')
        AddTextEntryByHash(0x76BDDC9C, 'Debadge Carbon Housing /w Carbon Cover')
        AddTextEntryByHash(0x7755A68A, 'X-Flow Monster')
        AddTextEntryByHash(0x7773B282, 'Remove Bonnet')
        AddTextEntryByHash(0x78E06943, 'Blast Pipes')
        AddTextEntryByHash(0x791F3BF2, 'Street Swine')
        AddTextEntryByHash(0x7BEB2010, 'Rotary Engine Swap')
        AddTextEntryByHash(0x7C4AF102, 'UN Edition (Red)')
        AddTextEntryByHash(0x7DBDDCA9, 'Primary Housing')
        AddTextEntryByHash(0x7DC1EE95, 'Bash Bar MK2')
        AddTextEntryByHash(0x7EA7196F, 'Lowlife Republic')
        AddTextEntryByHash(0x7FB0F6D6, 'Street15')
        AddTextEntryByHash(0x7FFBE125, 'Primary Housing /w Primary Cover')
        AddTextEntryByHash(0x83614E0E, 'Rear Arches')
        AddTextEntryByHash(0x8443AE45, "'Inverted' The Nation")
        AddTextEntryByHash(0x846EB7CC, 'Carbon Rear Housing')
        AddTextEntryByHash(0x8833806F, 'Debadge Secondary Housing')
        AddTextEntryByHash(0x88D9B553, 'Element MK2')
        AddTextEntryByHash(0x8945F090, 'Engine Swaps')
        AddTextEntryByHash(0x8959DC67, 'FR-Works')
        AddTextEntryByHash(0x89642ECE, 'FR-Works Diffuser')
        AddTextEntryByHash(0x89B20990, 'Fukaru')
        AddTextEntryByHash(0x8A6998FF, 'FR-Works')
        AddTextEntryByHash(0x8E25C485, 'Twin Turbo /w Secondary Engine Cover')
        AddTextEntryByHash(0x8E703F4F, 'Annimo Intercooler')
        AddTextEntryByHash(0x8EE2154A, 'Bigger Pipes')
        AddTextEntryByHash(0x8F25915C, 'Wangan')
        AddTextEntryByHash(0x8F7192A4, 'Element')
        AddTextEntryByHash(0x90D8BDD2, 'X-Flow')
        AddTextEntryByHash(0x91E49C35, 'Beater')
        AddTextEntryByHash(0x92041E90, 'Inverted Stars and Spikes')
        AddTextEntryByHash(0x935FD7DD, 'Intercooler')
        AddTextEntryByHash(0x967B2167, 'FR-Works')
        AddTextEntryByHash(0x993A9D8D, 'Front Arches')
        AddTextEntryByHash(0x9A19D054, 'Stars and Spikes')
        AddTextEntryByHash(0x9B83500D, 'FR-Works MK2')
        AddTextEntryByHash(0x9CA38694, 'V8 Engine Swap')
        AddTextEntryByHash(0x9DF3DD13, 'Wangan MK2')
        AddTextEntryByHash(0x9E45E1F1, 'Carbon Big Gaper MK2')
        AddTextEntryByHash(0x9FE9C488, 'Time Attack Splitter + Canards')
        AddTextEntryByHash(0x9FF9385E, 'wRONg Beater')
        AddTextEntryByHash(0xA0003311, 'Bash Bar')
        AddTextEntryByHash(0xA098E96B, 'Twin Turbo /w Primary Engine Cover')
        AddTextEntryByHash(0xA25B332E, 'Rear Badges')
        AddTextEntryByHash(0xA6A27C33, 'Painted Rear Housing')
        AddTextEntryByHash(0xA9148113, 'Secondary Rear Housing')
        AddTextEntryByHash(0xAA2C4819, 'Venture')
        AddTextEntryByHash(0xAA962279, 'TT V10 Engine Swap')
        AddTextEntryByHash(0xAAA08D39, 'Secondary Housing /w Carbon Cover')
        AddTextEntryByHash(0xAB19788C, 'Full Cage')
        AddTextEntryByHash(0xABD8A083, 'OEM Plus')
        AddTextEntryByHash(0xAC5474C9, 'Complaining Jane')
        AddTextEntryByHash(0xAC96110A, 'Oversized Spoiler')
        AddTextEntryByHash(0xAE6419FD, 'OEM Plus')
        AddTextEntryByHash(0xAEE81AD5, 'Bay Shore')
        AddTextEntryByHash(0xB0740341, 'Racing Cage')
        AddTextEntryByHash(0xB7148A51, 'Red Stripe')
        AddTextEntryByHash(0xB7F1124C, 'Monster Intercooler')
        AddTextEntryByHash(0xBA10EC8D, 'wRONg')
        AddTextEntryByHash(0xBCD9ED74, 'Venture MK2')
        AddTextEntryByHash(0xBCDD1217, 'FR-Works + Street Swine Front')
        AddTextEntryByHash(0xBED4B587, 'Ayanami-RS GT')
        AddTextEntryByHash(0xBFEEBD12, 'Annimo')
        AddTextEntryByHash(0xC096CE22, 'Carbon')
        AddTextEntryByHash(0xC169A52C, 'Padded Full Cage')
        AddTextEntryByHash(0xC16D75EB, 'Tuner')
        AddTextEntryByHash(0xC220CD13, 'Bay Shore')
        AddTextEntryByHash(0xC2F28A10, 'Twin Vented Arch')
        AddTextEntryByHash(0xC39B4ADC, 'Slatted')
        AddTextEntryByHash(0xC3AC29C2, 'Twin Fans Intercooler')
        AddTextEntryByHash(0xC4F44C39, 'Drag Wing')
        AddTextEntryByHash(0xC7C3DFF5, 'Annis Badge')
        AddTextEntryByHash(0xC7E4874A, 'Extended Bigger Pipes')
        AddTextEntryByHash(0xC98A2F3C, 'Touge Machine')
        AddTextEntryByHash(0xC9D8D0E6, 'Crimson')
        AddTextEntryByHash(0xCAFED302, 'Venture')
        AddTextEntryByHash(0xCBD50F1D, 'Cyberphonk')
        AddTextEntryByHash(0xCC783F3D, 'Carbon Big Gaper')
        AddTextEntryByHash(0xCD001E31, 'HFS Cannon')
        AddTextEntryByHash(0xCD6EB33A, 'FR-Works')
        AddTextEntryByHash(0xCE5E12E7, 'Atomic Drift')
        AddTextEntryByHash(0xD019D811, 'Tuner Wing')
        AddTextEntryByHash(0xD07769C0, 'Wangan')
        AddTextEntryByHash(0xD0C163D3, 'Winglet')
        AddTextEntryByHash(0xD2A1416A, 'HFS x SUMO')
        AddTextEntryByHash(0xD596229F, 'In the Depths of the Future')
        AddTextEntryByHash(0xD60AF0E6, 'Carbon Bullnose Mk3')
        AddTextEntryByHash(0xD62323C7, 'Even Bigger Pipes')
        AddTextEntryByHash(0xD84DA45F, 'Twin Vented')
        AddTextEntryByHash(0xDB8C744D, 'Crimson MK2')
        AddTextEntryByHash(0xDDC6053E, 'Painted Generic Arch')
        AddTextEntryByHash(0xDFA0436B, 'Painted Generic Arch')
        AddTextEntryByHash(0xE027B67A, 'Lozspeed Drift')
        AddTextEntryByHash(0xE081B5B2, 'OEM Plus + Curved Splitter')
        AddTextEntryByHash(0xE25F7C9C, 'Dracula')
        AddTextEntryByHash(0xE337DECC, 'Alien')
        AddTextEntryByHash(0xE4F70D8B, 'Bullnose MK2')
        AddTextEntryByHash(0xE5438264, 'Wangan')
        AddTextEntryByHash(0xE54FE6C7, 'Groovy Angel')
        AddTextEntryByHash(0xE5E508CE, 'Venture MK2')
        AddTextEntryByHash(0xE6BD6FD3, 'Padded Racing Cage')
        AddTextEntryByHash(0xE7460BC0, 'Crest MK2')
        AddTextEntryByHash(0xE763C63A, 'Yours')
        AddTextEntryByHash(0xE97CD72A, 'Removed Exhaust')
        AddTextEntryByHash(0xEA9A1794, 'X-Flow MK2')
        AddTextEntryByHash(0xEAE09819, 'Annimo Combo')
        AddTextEntryByHash(0xEB5A4E35, 'Single Pipe')
        AddTextEntryByHash(0xEC27CCC3, 'Bash Bar MK3')
        AddTextEntryByHash(0xEE08044C, 'Primary Engine Cover')
        AddTextEntryByHash(0xEE2E4ECB, 'OEM Plus + Sports Splitter')
        AddTextEntryByHash(0xEE6952FD, 'Street Swine')
        AddTextEntryByHash(0xEE69D53E, 'The Nation')
        AddTextEntryByHash(0xEE9B647C, 'Trunk')
        AddTextEntryByHash(0xEF6352A6, 'Annimo')
        AddTextEntryByHash(0xEFBA1767, 'Debadge Primary Housing /w Secondary Cover')
        AddTextEntryByHash(0xF09578D3, 'Roxanne')
        AddTextEntryByHash(0xF1B5E796, 'Generic Arch')
        AddTextEntryByHash(0xF288B25D, 'Cyclone Motor Swap')
        AddTextEntryByHash(0xF2E3A964, 'Bullnose')
        AddTextEntryByHash(0xF44C2AF8, 'X-Flow')
        AddTextEntryByHash(0xF46E20D3, 'Secondary Housing')
        AddTextEntryByHash(0xF4CEF8D3, 'FR-Works Wide MK2')
        AddTextEntryByHash(0xF5632E6B, 'Slatted MK2')
        AddTextEntryByHash(0xF69638B0, 'Carbon Slatted')
        AddTextEntryByHash(0xF7919C25, 'Remove Bumper')
        AddTextEntryByHash(0xF7A16051, 'OEM Plus + Race Splitter')
        AddTextEntryByHash(0xF7D76372, 'Annimo MK3')
        AddTextEntryByHash(0xF80E27F9, 'Race Wing')
        AddTextEntryByHash(0xF99BEAB8, 'Extended Even Bigger Pipes')
        AddTextEntryByHash(0xFA4D3E24, 'Pumped Arch Mk3')
        AddTextEntryByHash(0xFB41FAB4, 'Extended HFS Cannon')
        AddTextEntryByHash(0xFB6C6D03, 'Bayshore LS-Swap')
        AddTextEntryByHash(0xFD137291, 'Fujiwara')
        AddTextEntryByHash(0xFD273CA6, 'Annimo Tail')
        AddTextEntryByHash(0xFE4D5DCA, 'Primary Cover')
end)


function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry('VMT_REMUSTWO_PULLEY','Vernier Pulleys / Pulley Covers')
	AddTextEntry('VMT_REMUSTWO_ENGCOVER','Valve Covers')
	AddTextEntry('VMT_REMUSTWO_BRACE','Strut Braces')
	AddTextEntry('VMT_REMUSTWO_FILTER','Air Filters / Aspiration Options')
	AddTextEntry('VMT_REMUSTWO_ROOFSCOOP','Roof Scoops')
	AddTextEntry('VMT_REMUSTWO_ROOFSPOILER','Roof Spoilers')
	AddTextEntry('VMT_REMUSTWO_MIRROR','Door Mirrors')
	AddTextEntry('VMT_REMUSTWO_BADGES','Badges')
	AddTextEntry('VMT_REMUSTWO_EYELID','Headlight Eyelids')
	AddTextEntry('VMT_REMUSTWO_HEADLIGHTS','Headlights')
	AddTextEntry('VMT_REMUSTWO_GEARKNOB','Gear Knob')
	AddTextEntry('VMT_REMUSTWO_DASHTRIM','Dashboard Trim')
	AddTextEntry('VMT_REMUSTWO_DASHB','Dashboard')
	AddTextEntry('VMT_REMUSTWO_ROLLB','Roll Cages')
	AddTextEntry('VMT_REMUSTWO_WEIGHTR','Weight Reduction')
	AddTextEntry('VMT_REMUSTWO_GAUGES','Gauges')
	AddTextEntry('VMT_REMUSTWO_DOORC','Door Cards')
	AddTextEntry('REMUSTWO','Remus II')
	AddTextEntry('REMUSTWO_BUMF1','T-Sport Front Bumper')
	AddTextEntry('REMUSTWO_BUMF2','T-Sport II Front Bumper')
	AddTextEntry('REMUSTWO_BUMF2A','T-Sport II Front Bumper V2')
	AddTextEntry('REMUSTWO_BUMF3','Zenith Front Bumper')
	AddTextEntry('REMUSTWO_BUMF3A','Zenith Front Bumper V2')
	AddTextEntry('REMUSTWO_BUMF3B','Zenith Front Bumper V3')
	AddTextEntry('REMUSTWO_BUMF4','Kashihara Front Bumper')
	AddTextEntry('REMUSTWO_BUMF5','Race Front Bumper')
	AddTextEntry('REMUSTWO_BUMF6','Euro 2000 Front Bumper')
	AddTextEntry('REMUSTWO_BUMF7','X-Flow R-Spec Front Bumper')
	AddTextEntry('REMUSTWO_BUMF8','X-Flow Redacted Front Bumper')
	AddTextEntry('REMUSTWO_BUMF9','Alien J12 Front Bumper')
	AddTextEntry('REMUSTWO_BUMF9A','Alien J12 Front Bumper V2')
	AddTextEntry('REMUSTWO_BUMR1','T-Sport Rear Bumper')
	AddTextEntry('REMUSTWO_BUMR2','T-Sport II Rear Bumper')
	AddTextEntry('REMUSTWO_BUMR3','Zenith Rear Bumper')
	AddTextEntry('REMUSTWO_BUMR4','Kashihara Rear Bumper')
	AddTextEntry('REMUSTWO_BUMR5','Race Rear Bumper')
	AddTextEntry('REMUSTWO_BUMR6','Euro 2000 Rear Bumper')
	AddTextEntry('REMUSTWO_BUMR7','X-Flow R-Spec Rear Bumper')
	AddTextEntry('REMUSTWO_BUMR8','X-Flow Redacted Rear Bumper')
	AddTextEntry('REMUSTWO_BUMR9','Alien J12 Rear Bumper')
	AddTextEntry('REMUSTWO_SKIRT2','T-Sport Side Skirts')
	AddTextEntry('REMUSTWO_SKIRT3','Zenith Side Skirts')
	AddTextEntry('REMUSTWO_SKIRT4','Kashihara Side Skirts')
	AddTextEntry('REMUSTWO_SKIRT5','Race Side Skirts')
	AddTextEntry('REMUSTWO_SKIRT6','Euro 2000 Side Skirts')
	AddTextEntry('REMUSTWO_SKIRT7','X-Flow R-Spec Side Skirts')
	AddTextEntry('REMUSTWO_SKIRT8','X-Flow Redacted Side Skirts')
	AddTextEntry('REMUSTWO_SKIRT9','Alien J12 Side Skirts')
	AddTextEntry('REMUSTWO_RSCOOP1','Sports Roof Scoop')
	AddTextEntry('REMUSTWO_RSCOOP1A','Carbon Sports Roof Scoop')
	AddTextEntry('REMUSTWO_RSCOOP2','Race Roof Scoop')
	AddTextEntry('REMUSTWO_RSCOOP2A','Carbon Race Roof Scoop')
	AddTextEntry('REMUSTWO_ROOF1','Painted Roof Spoiler')
	AddTextEntry('REMUSTWO_ROOF1A','Carbon Roof Spoiler')
	AddTextEntry('REMUSTWO_ROOF2','Painted Sport Roof Spoiler')
	AddTextEntry('REMUSTWO_ROOF2A','Carbon Sport Roof Spoiler')
	AddTextEntry('REMUSTWO_BADGELINK_B','T-Sport Badges')
	AddTextEntry('REMUSTWO_REMGRILLE','Remove Grill')
	AddTextEntry('REMUSTWO_GRILLE0','Painted Stock Grill')
	AddTextEntry('REMUSTWO_GRILLE0A','Carbon Stock Grill')
	AddTextEntry('REMUSTWO_GRILLE1','Plastic T-Sport Grill')
	AddTextEntry('REMUSTWO_GRILLE1A','Painted T-Sport Grill')
	AddTextEntry('REMUSTWO_GRILLE1B','Carbon T-Sport Grill')
	AddTextEntry('REMUSTWO_GRILLE2','Plastic Split Grill')
	AddTextEntry('REMUSTWO_GRILLE2A','Painted Split Grill')
	AddTextEntry('REMUSTWO_GRILLE2B','Carbon Split Grill')
	AddTextEntry('REMUSTWO_GRILLE3','Plastic Tuner Grill')
	AddTextEntry('REMUSTWO_GRILLE3A','Painted Tuner Grill')
	AddTextEntry('REMUSTWO_GRILLE3B','Carbon Tuner Grill')
	AddTextEntry('REMUSTWO_GRILLE4','Plastic Flat Grill')
	AddTextEntry('REMUSTWO_GRILLE4A','Painted Flat Grill')
	AddTextEntry('REMUSTWO_GRILLE4B','Carbon Flat Grill')
	AddTextEntry('REMUSTWO_MIRROR_0A','Carbon Stock Mirrors')
	AddTextEntry('REMUSTWO_MIRROR_1','Plastic Race Mirrors')
	AddTextEntry('REMUSTWO_MIRROR_1A','Painted Race Mirrors')
	AddTextEntry('REMUSTWO_MIRROR_1B','Carbon Race Mirrors')
	AddTextEntry('WHEELREM_SPT_01','T-Sport')
	AddTextEntry('WHEELREM_SPT_02','T-Sport Chrome')
	AddTextEntry('REMUSTWO_EXH0','Short T-Sport Exhaust')
	AddTextEntry('REMUSTWO_EXH0_BRNT','Burnt Short T-Sport Exhaust')
	AddTextEntry('REMUSTWO_EXH0A','Long T-Sport Exhaust')
	AddTextEntry('REMUSTWO_EXH0A_BRNT','Burnt Long T-Sport Exhaust')
	AddTextEntry('REMUSTWO_EXH1','Short Twin Tip Exhaust')
	AddTextEntry('REMUSTWO_EXH1_BRNT','Burnt Short Twin Tip Exhaust')
	AddTextEntry('REMUSTWO_EXH1A','Long Twin Tip Exhaust')
	AddTextEntry('REMUSTWO_EXH1A_BRNT','Burnt Long Twin Tip Exhaust')
	AddTextEntry('REMUSTWO_EXH2','Short Big Bore Exhaust')
	AddTextEntry('REMUSTWO_EXH2_EXTRA','Short Silenced Big Bore Exhaust')
	AddTextEntry('REMUSTWO_EXH2_BRNT','Burnt Short Big Bore Exhaust')
	AddTextEntry('REMUSTWO_EXH2_BRNT_EXTRA','Burnt Short Silenced Big Bore Exhaust')
	AddTextEntry('REMUSTWO_EXH2A','Long Big Bore Exhaust')
	AddTextEntry('REMUSTWO_EXH2A_EXTRA','Long Silenced Big Bore Exhaust')
	AddTextEntry('REMUSTWO_EXH2A_BRNT','Burnt Long Big Bore Exhaust')
	AddTextEntry('REMUSTWO_EXH2A_BRNT_EXTRA','Burnt Long Silenced Big Bore Exhaust')
	AddTextEntry('REMUSTWO_EXH3','Short Slash Cut Exhaust')
	AddTextEntry('REMUSTWO_EXH3_BRNT','Burnt Short Slash Cut Exhaust')
	AddTextEntry('REMUSTWO_EXH3A','Long Slash Cut Exhaust')
	AddTextEntry('REMUSTWO_EXH3A_BRNT','Burnt Long Slash Cut Exhaust')
	AddTextEntry('REMUSTWO_EXH4','Short Shotgun Exhaust')
	AddTextEntry('REMUSTWO_EXH4_BRNT','Burnt Short Shotgun Exhaust')
	AddTextEntry('REMUSTWO_EXH4A','Long Shotgun Exhaust')
	AddTextEntry('REMUSTWO_EXH4A_BRNT','Burnt Long Shotgun Exhaust')
	AddTextEntry('REMUSTWO_EXH5','Short Heart Exhaust')
	AddTextEntry('REMUSTWO_EXH5A','Painted Short Heart Exhaust')
	AddTextEntry('REMUSTWO_EXH5_BRNT','Burnt Short Heart Exhaust')
	AddTextEntry('REMUSTWO_EXH5A_BRNT','Painted Burnt Short Heart Exhaust')
	AddTextEntry('REMUSTWO_EXH5B','Long Heart Exhaust')
	AddTextEntry('REMUSTWO_EXH5B_BRNT','Burnt Long Heart Exhaust')
	AddTextEntry('REMUSTWO_EXH5C','Painted Long Heart Exhaust')
	AddTextEntry('REMUSTWO_EXH5C_BRNT','Painted Burnt Long Heart Exhaust')
	AddTextEntry('REMUSTWO_REMHOOD','Remove Hood')
	AddTextEntry('REMUSTWO_BON0','Carbon Stock Hood')
	AddTextEntry('REMUSTWO_BON1','Smooth Hood')
	AddTextEntry('REMUSTWO_BON1A','Carbon Smooth Hood')
	AddTextEntry('REMUSTWO_BON2','Drift Hood')
	AddTextEntry('REMUSTWO_BON2A','Carbon Drift Hood')
	AddTextEntry('REMUSTWO_BON3','T-Sport Hood')
	AddTextEntry('REMUSTWO_BON3A','Carbon T-Sport Hood')
	AddTextEntry('REMUSTWO_BON4','T-Sport II Hood')
	AddTextEntry('REMUSTWO_BON4A','Carbon T-Sport II Hood')
	AddTextEntry('REMUSTWO_BON5','X-Flow Redacted Hood')
	AddTextEntry('REMUSTWO_BON5A','Carbon X-Flow Redacted Hood')
	AddTextEntry('REMUSTWO_SPOILER1','T-Sport Spoiler')
	AddTextEntry('REMUSTWO_SPOILER1A','Carbon T-Sport Spoiler')
	AddTextEntry('REMUSTWO_SPOILER2','T-Sport II Spoiler')
	AddTextEntry('REMUSTWO_SPOILER2A','Carbon T-Sport II Spoiler')
	AddTextEntry('REMUSTWO_SPOILER3','Sport Spoiler')
	AddTextEntry('REMUSTWO_SPOILER3A','Carbon Sport Spoiler')
	AddTextEntry('REMUSTWO_SPOILER4','Low Level Spoiler')
	AddTextEntry('REMUSTWO_SPOILER4A','Carbon Low Level Spoiler')
	AddTextEntry('REMUSTWO_SPOILER5','Zenith Spoiler')
	AddTextEntry('REMUSTWO_SPOILER5A','Carbon Zenith Spoiler')
	AddTextEntry('REMUSTWO_SPOILER6','Tuner Spoiler')
	AddTextEntry('REMUSTWO_SPOILER6A','Carbon Tuner Spoiler')
	AddTextEntry('REMUSTWO_SPOILER7','Drift Spoiler')
	AddTextEntry('REMUSTWO_SPOILER7A','Carbon Drift Spoiler')
	AddTextEntry('REMUSTWO_ENGCOV1','Carbon Valve Cover')
	AddTextEntry('REMUSTWO_ENGCOV2','Camo Valve Cover')
	AddTextEntry('REMUSTWO_ENGCOV3','Skull Valve Cover')
	AddTextEntry('REMUSTWO_ENGCOV1A','Carbon Pulley Cover')
	AddTextEntry('REMUSTWO_ENGCOV2A','Camo Pulley Cover')
	AddTextEntry('REMUSTWO_ENGCOV3A','Skull Pulley Cover')
	AddTextEntry('REMUSTWO_PULLEYS_1','Black Exposed Vernier Pulleys')
	AddTextEntry('REMUSTWO_PULLEYS_2','Red Exposed Vernier Pulleys')
	AddTextEntry('REMUSTWO_PULLEYS_3','Blue Exposed Vernier Pulleys')
	AddTextEntry('REMUSTWO_PULLEYS_4','Purple Exposed Vernier Pulleys')
	AddTextEntry('REMUSTWO_FILTER1','Red Cone Filter')
	AddTextEntry('REMUSTWO_FILTER1A','Painted Cone Filter')
	AddTextEntry('REMUSTWO_FILTER2','Carbon Horn Filter')
	AddTextEntry('REMUSTWO_FILTER2A','Painted Horn Filter')
	AddTextEntry('REMUSTWO_FILTER3','Green Mushroom Filter')
	AddTextEntry('REMUSTWO_FILTER3A','Painted Mushroom Filter')
	AddTextEntry('REMUSTWO_FILTER4','Green Box Filter')
	AddTextEntry('REMUSTWO_FILTER4A','Painted Box Filter')
	AddTextEntry('REMUSTWO_TURBO_1','Single Turbo w/ No Filter')
	AddTextEntry('REMUSTWO_TURBO_FILTER1','Single Turbo w/ Red Cone Filter')
	AddTextEntry('REMUSTWO_TURBO_FILTER1A','Single Turbo w/ Painted Cone Filter')
	AddTextEntry('REMUSTWO_TURBO_FILTER2','Single Turbo w/ Carbon Horn Filter')
	AddTextEntry('REMUSTWO_TURBO_FILTER2A','Single Turbo w/ Painted Horn Filter')
	AddTextEntry('REMUSTWO_TURBO_FILTER3','Single Turbo w/ Green Mushroom Filter')
	AddTextEntry('REMUSTWO_TURBO_FILTER3A','Single Turbo w/ Painted Mushroom Filter')
	AddTextEntry('REMUSTWO_TURBO_FILTER4','Single Turbo w/ Green Box Filter')
	AddTextEntry('REMUSTWO_TURBO_FILTER4A','Single Turbo w/ Painted Box Filter')
	AddTextEntry('REMUSTWO_BRACE1','Polished Strut Brace')
	AddTextEntry('REMUSTWO_BRACE1A','Painted Strut Brace')
	AddTextEntry('REMUSTWO_BRACE1B','Carbon Strut Brace')
	AddTextEntry('REMUSTWO_BRACE2','Wide Titanium Strut Brace')
	AddTextEntry('REMUSTWO_BRACE2A','Wide Painted Strut Brace')
	AddTextEntry('REMUSTWO_BRACE2B','Wide Carbon Strut Brace')
	AddTextEntry('REMUSTWO_BRACE3','Triangulated Strut Brace')
	AddTextEntry('REMUSTWO_BRACE3A','Painted Triangulated Strut Brace')
	AddTextEntry('REMUSTWO_BRACE3B','Carbon Triangulated Strut Brace')
	AddTextEntry('REMUSTWO_BRACE4','Titanium Twin Bar Strut Brace')
	AddTextEntry('REMUSTWO_BRACE4A','Painted Twin Bar Strut Brace')
	AddTextEntry('REMUSTWO_BRACE4B','Carbon Twin Bar Strut Brace')
	AddTextEntry('REMUSTWO_BRACE5','Lightweight Polished Strut Brace')
	AddTextEntry('REMUSTWO_BRACE5A','Lightweight Painted Strut Brace')
	AddTextEntry('REMUSTWO_BRACE5B','Lightweight Carbon Strut Brace')
	AddTextEntry('REMUSTWO_BRACE6','Polished V-Bar Strut Brace')
	AddTextEntry('REMUSTWO_BRACE6A','Painted V-Bar Strut Brace')
	AddTextEntry('REMUSTWO_BRACE6B','Carbon V-Bar Strut Brace')
	AddTextEntry('REMUSTWO_BRACE7','Polished Race Strut Brace')
	AddTextEntry('REMUSTWO_BRACE7A','Painted Race Strut Brace')
	AddTextEntry('REMUSTWO_BRACE7B','Carbon Race Strut Brace')
	AddTextEntry('REMUSTWO_EYELIDS1','Plastic Sleepy Eyelids')
	AddTextEntry('REMUSTWO_EYELIDS1A','Painted Sleepy Eyelids')
	AddTextEntry('REMUSTWO_EYELIDS1B','Carbon Sleepy Eyelids')
	AddTextEntry('REMUSTWO_EYELIDS2','Plastic Aggressive Eyelids')
	AddTextEntry('REMUSTWO_EYELIDS2A','Painted Aggressive Eyelids')
	AddTextEntry('REMUSTWO_EYELIDS2B','Carbon Aggressive Eyelids')
	AddTextEntry('REMUSTWO_LIGHTS1','Plastic Tuner Headlights')
	AddTextEntry('REMUSTWO_LIGHTS1A','Painted Tuner Headlights')
	AddTextEntry('REMUSTWO_LIGHTS1B','Carbon Tuner Headlights')
	AddTextEntry('REMUSTWO_STOCKL0A','Painted Stock Headlights')
	AddTextEntry('REMUSTWO_STOCKL0B','Carbon Stock Headlights')
	AddTextEntry('REMUSTWO_LIGHTS0','Plastic T-Sport Headlights')
	AddTextEntry('REMUSTWO_LIGHTS0A','Painted T-Sport Headlights')
	AddTextEntry('REMUSTWO_LIGHTS0B','Carbon T-Sport Headlights')
	AddTextEntry('REMUSTWO_GEARKNOB_1','Polished T-Sport Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_1A','Painted T-Sport Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_1B','Carbon T-Sport Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_2','Polished Lightweight Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_2A','Painted Lightweight Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_2B','Carbon Lightweight Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_3','Polished Spherical Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_3A','Painted Spherical Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_3B','Carbon Spherical Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_4','Polished Annis Branded Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_4A','Painted Annis Branded Gear Knob')
	AddTextEntry('REMUSTWO_GEARKNOB_4B','Carbon Annis Branded Gear Knob')
	AddTextEntry('REMUSTWO_DASHTRIM_0','Stripped Plastic Dashboard Trim')
	AddTextEntry('REMUSTWO_DASHTRIM_1','Wooden Dashboard Trim')
	AddTextEntry('REMUSTWO_DASHTRIM_1A','Stripped Wooden Dashboard Trim')
	AddTextEntry('REMUSTWO_DASHTRIM_2','Carbon Dashboard Trim')
	AddTextEntry('REMUSTWO_DASHTRIM_2A','Stripped Carbon Dashboard Trim')
	AddTextEntry('REMUSTWO_DASH_0A','Lightweight Dashboard')
	AddTextEntry('REMUSTWO_DASH_1','Flocked Dashboard')
	AddTextEntry('REMUSTWO_DASH_1A','Lightweight Flocked Dashboard')
	AddTextEntry('REMUSTWO_DASH_2','Carbon Dashboard')
	AddTextEntry('REMUSTWO_DASH_2A','Lightweight Carbon Dashboard')
	AddTextEntry('REMUSTWO_INTERIOR1','Semi Stripped Interior')
	AddTextEntry('REMUSTWO_INTERIOR1A','Stripped Interior w/ Fire Suppression System')
	AddTextEntry('REMUSTWO_INTERIOR1B','Stripped Interior w/ Full Race Preparation')
	AddTextEntry('REMUSTWO_DOORCARDS_0','Flocked Door Cards')
	AddTextEntry('REMUSTWO_DOORCARDS_0A','Carbon Door Cards')
	AddTextEntry('REMUSTWO_DOORCARDS_1','Lightweight Flocked Door Cards')
	AddTextEntry('REMUSTWO_DOORCARDS_1A','Lightweight Carbon Door Cards')
	AddTextEntry('REMUSTWO_DOORCARDS_1B','Lightweight Aluminium Door Cards')
	AddTextEntry('REMUSTWO_CAGE_1','Polished Street Half Cage')
	AddTextEntry('REMUSTWO_CAGE_1A','Painted Street Half Cage')
	AddTextEntry('REMUSTWO_CAGE_2','Polished Dash Dodger Cage')
	AddTextEntry('REMUSTWO_CAGE_2A','Painted Dash Dodger Cage')
	AddTextEntry('REMUSTWO_CAGE_3','Polished Full Roll Cage')
	AddTextEntry('REMUSTWO_CAGE_3A','Painted Full Roll Cage')
	AddTextEntry('REMUSTWO_STWHEEL_1','Apex Basic Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_2','Apex Clubman Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_3','Apex Professional Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_4','Formula Basic Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_5','Formula Clubman Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_6','Formula Professional Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_7','Sprint Basic Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_8','Sprint Clubman Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_9','Sprint Professional Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_10','Lightweight Basic Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_11','Lightweight Clubman Steering Wheel')
	AddTextEntry('REMUSTWO_STWHEEL_12','Lightweight Professional Steering Wheel')
	AddTextEntry('REMUSTWO_SEATS_1','Painted T-Sport Seats')
	AddTextEntry('REMUSTWO_SEATS_1A','Lightweight T-Sport Seats')
	AddTextEntry('REMUSTWO_SEATS_1B','Lightweight Carbon T-Sport Seats')
	AddTextEntry('REMUSTWO_SEATS_2','Painted Tuner Seats')
	AddTextEntry('REMUSTWO_SEATS_2A','Lightweight Tuner Seats')
	AddTextEntry('REMUSTWO_SEATS_2B','Lightweight Carbon Tuner Seats')
	AddTextEntry('REMUSTWO_SEATS_3','Painted Bucket Seats')
	AddTextEntry('REMUSTWO_SEATS_3A','Lightweight Bucket Seats')
	AddTextEntry('REMUSTWO_SEATS_3B','Lightweight Carbon Bucket Seats')
	AddTextEntry('REMUSTWO_DIALS_BOOST','Dash Mounted Boost Gauge')
	AddTextEntry('REMUSTWO_DIALS_RPM','Dash Mounted RPM Gauge')
	AddTextEntry('REMUSTWO_DIALS_BSTRPM','Dash Mounted RPM & Boost Gauges')
	AddTextEntry('REMUSTWO_DIALS_RACE','Race Gauges')
	AddTextEntry('REMUSTWO_DIALS_RACEB','Race Gauges w/ Dash Mounted Boost Gauge')
	AddTextEntry('REMUSTWO_DIALS_RACEC','Race Gauges w/ Dash Mounted RPM Gauge')
	AddTextEntry('REMUSTWO_DIALS_RACED','Race Gauges w/ Dash Mounted RPM & Boost Gauges')
	AddTextEntry('REMUSTWO_LIVERY2','Clicklovers Black Livery')	
	AddTextEntry('REMUSTWO_LIVERY2A','Clicklovers White Livery')	
	AddTextEntry('REMUSTWO_LIVERY3','Two Tone Livery')	
	AddTextEntry('REMUSTWO_LIVERY3A','RBS Performance Livery')	
	AddTextEntry('REMUSTWO_LIVERY4','Kisama x CunTech Black Livery')	
	AddTextEntry('REMUSTWO_LIVERY4A','Kisama x CunTech White Livery')
	AddTextEntry('REMUSTWO_LIVERY5','Smooth Thinkers Black Livery')		
	AddTextEntry('REMUSTWO_LIVERY5A','Smooth Thinkers White Livery')		
	AddTextEntry('REMUSTWO_LIVERY6','Alien x X-Flow Livery')		
	AddTextEntry('REMUSTWO_LIVERY7','Auto Exotic Drift Livery')		
	AddTextEntry('REMUSTWO_LIVERY8','Star Screamers Livery')			
	AddTextEntry('REMUSTWO_LIVERY10','"Dont Leave Town" Livery')		
	AddTextEntry('REMUSTWO_LIVERY11','"See Ya!" Livery')		
end)