fx_version 'cerulean'
games { 'rdr3', 'gta5' }

author "Spirit's Creations"
description 'Lore-Friendly Car Pack'
version 'v1.0.0'
repository 'https://github.com/SpiritsCreations/FiveM-Lore-Friendly-Car-Pack'

files {
    'data/**/*.meta',
    'data/**/*.xml',
    'data/**/*.dat',
    'data/**/*.ytyp',
    'audio/audioconfig/*.dat151.rel',
    'audio/audioconfig/*.dat151.nametable',
    'audio/audioconfig/*.dat54.rel',
    'audio/audioconfig/*.dat54.nametable',
    'audio/audioconfig/*.dat10.rel',
    'audio/audioconfig/*.dat10.nametable',
    'audio/sfx/**/*.awc'
}

data_file 'HANDLING_FILE' 'data/**/*.meta'
data_file 'VEHICLE_METADATA_FILE' 'data/**/*.meta'
data_file 'CARCOLS_FILE' 'data/**/*.meta'
data_file 'VEHICLE_LAYOUTS_FILE' 'data/**/*.meta'
data_file 'VEHICLE_VARIATION_FILE' 'data/**/*.meta'
data_file 'VEHICLE_SHOP_DLC_FILE' 'data/**/*.meta'
data_file 'CONTENT_UNLOCKING_META_FILE' 'data/**/*.meta' 
data_file 'VEHICLE_SETTINGS_FILE' 'data/**/*.meta'
data_file 'CAR_ADDON_CONTENT_UNLOCKS' 'data/**/*.meta'
data_file 'PTFXASSETINFO_FILE' 'data/**/ptfxassetinfo.meta'

client_scripts {
    'vehicle_names.lua',
    'client.lua'
}

server_script 'versioncheck.lua'

-- START OF AUDIO SYNTHDATA --
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/bfely_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/blisgpr_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/contenderc_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/dlc98s1_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/gresleyh_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/hachura_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/infernussr_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/italigton_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/meteor_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/monroec_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/scharmann_amp.dat'
data_file 'AUDIO_SYNTHDATA' 'audio/audioconfig/stratumc_amp.dat'
-- END OF AUDIO SYNTHDATA

-- START OF AUDIO GAMEDATA --
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/711pfister_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/alphav_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/argento_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/ariant_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/arias_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/bansheepo_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/bati901_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/bfely_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/blisgpr_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/boorc_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/buffaloh_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/callista_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/castella_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/contenderc_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/coquette4c_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/cw2019_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/cypherct_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/deimos_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/dlc98s1_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/dom645_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/drod_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/elegyrh7_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/elegyx_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/euros_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/fmjgte_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/gresleyh_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/gspeedster_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/hachura_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/hpr1_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/infernussr_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/italigton_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/jdoraclev12_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/jdvigeror_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/kawaii_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/kriegerc_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/majimagt_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/majimalm_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/matador_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/meteor_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/mf1_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/mf1c_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/monroec_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/nebulaw_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/nsandstorm_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/nspeedo_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/nw_jester_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/oracxsle_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/picadorexr_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/r255_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/rebeld_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/remustwo_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/rh4_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/rotary7_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/roxanne_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/rqzr1_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sancy_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/scharmann_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/scharmannv8_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sentgtr_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sentineldm_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sentinelsg3_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sentinelsg4_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/severo_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sheavas_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sigma3_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/spritzer_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/spritzerdtm_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/stratumc_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sultan2c_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sultanrsv8_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/sunrise_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/supergts_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/tachyon_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/tampar_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/tamx_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/tempestarc_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/turismo2lm_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/turismoc_game.dat'
-- data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/unmarkedtorr_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/urban_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/ventoso_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/vorstand_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/vulture_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/wibvelox_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/zionks_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/zionv10_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/zodiac_game.dat'
data_file 'AUDIO_GAMEDATA' 'audio/audioconfig/zr250_game.dat'
-- END OF AUDIO GAMEDATA --

-- START OF AUDIO SOUNDDATA --
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/711pfister_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/alphav_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/argento_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/ariant_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/arias_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/bansheepo_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/bati901_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/bfely_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/blisgpr_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/boorc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/buffaloh_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/callista_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/castella_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/contenderc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/coquette4c_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/cw2019_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/cypherct_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/deimos_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/dlc98s1_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/dom645_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/drod_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/elegyrh7_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/elegyx_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/euros_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/fmjgte_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/gresleyh_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/hachura_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/hpr1_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/infernussr_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/italigton_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/jdoraclev12_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/jdvigeror_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/kawaii_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/kriegerc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/majimagt_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/majimalm_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/matador_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/meteor_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/mf1_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/mf1c_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/monroec_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/monroer_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/nspeedo_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/oracxsle_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/picadorexr_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/r255_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/rebeld_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/remustwo_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/rh4_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/rotary7_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/roxanne_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/rqzr1_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sancy_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/scharmann_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/scharmannv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sentgtr_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sentineldm_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sentinelsg3_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sentinelsg3d_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sentinelsg4_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/severo_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sheavas_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sigma3_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/spritzer_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/spritzerdtm_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/stratumc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sultan2c_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sultanrsv8_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/sunrise_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/supergts_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/tachyon_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/tampar_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/tamx_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/tempestarc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/turismo2lm_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/turismoc_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/urban_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/ventoso_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/vorstand_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/vulture_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/wibvelox_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/zionks_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/zionv10_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/zodiac_sounds.dat'
data_file 'AUDIO_SOUNDDATA' 'audio/audioconfig/zr250_sounds.dat'
-- END OF AUDIO SOUNDDATA --

-- START OF AUDIO WAVEPACK --
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_98s1'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_711pfister'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_alphav'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_argento'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_ariant'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_bansheepo'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_bati901'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_bfely'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_blisgpr'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_boorc'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_callista'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_castella'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_contenderc'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_coquette4c'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_cw2019'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_cypherct'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_deimos'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_dom645'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_drod'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_elegyx'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_fmjgte'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_gresleyh'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_gtrsent'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_hachura'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_hpr1'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_infernussr'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_italigton'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_jdoraclev12'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_jdvigeror'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_jdvigerord'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_kawaii'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_kriegerc'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_majimagt'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_matador'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_meteor'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_monroec'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_monroer'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_nspeedo'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_nw_jester'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_oracxsle'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_picadorexr'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_progenmf1'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_r255'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_rebeld'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_remustwo'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_rh4elegy'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_rh7elegy'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_roxanne'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_rqzr1'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_sancy'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_scharmann'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_scharmannv8'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_sentinelsg4'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_severo'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_sheavas'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_sigma3'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_spritzer'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_stewarias'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_sultan2c'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_sunrise'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_supergts'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_tachyon'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_tampar'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_tampax'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_tempestarc'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_trumpetzr'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_turismo2lm'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_turismoc'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_uberv10'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_urban'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_usentinelsg3'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_v8sultanrs'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_velox'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_vorstand'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_vulture'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_warrenerb'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_wibzionv10'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_zionks'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_zionv10'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_zodiac'
data_file 'AUDIO_WAVEPACK' 'audio/sfx/dlc_zr250'
-- END OF AUDIO WAVEPACK --

