function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddTextEntry('cii_roti_1', "Velocity X")
    AddTextEntry('cii_roti_1_v', "Velocity X Accents")
    AddTextEntry('cii_roti_2', "Turbo Edge")
    AddTextEntry('cii_roti_2_v', "Turbo Edge Accents")
    AddTextEntry('cii_roti_3', "Nitro Drift")
    AddTextEntry('cii_roti_3_v', "Nitro Drift Accents")
    AddTextEntry('cii_roti_4', "Cyclone Z")
    AddTextEntry('cii_roti_4_v', "Cyclone Z Accents")
    AddTextEntry('cii_roti_5', "Razorback")
    AddTextEntry('cii_roti_5_v', "Razorback Accents")
    AddTextEntry('cii_roti_6', "Hyperion")
    AddTextEntry('cii_roti_6_v', "Hyperion Accents")
    AddTextEntry('cii_roti_7', "Apex V2")
    AddTextEntry('cii_roti_7_v', "Apex V2 Accents")
    AddTextEntry('cii_roti_8', "Striker X")
    AddTextEntry('cii_roti_8_v', "Striker X Accents")
    AddTextEntry('cii_roti_9', "Vortex R")
    AddTextEntry('cii_roti_9_v', "Vortex R Accents")
    AddTextEntry('cii_roti_10', "VeloStar")
    AddTextEntry('cii_roti_10_v', "VeloStar Accents")
    AddTextEntry('cii_roti_11', "Phantom GT")
    AddTextEntry('cii_roti_11_v', "Phantom GT Accents")
    AddTextEntry('cii_roti_12', "Zenith Pro")
    AddTextEntry('cii_roti_12_v', "Zenith Pro Accents")
    AddTextEntry('cii_voss_1', "Flux Racer")
    AddTextEntry('cii_voss_1_v', "Flux Racer Accents")
    AddTextEntry('cii_voss_2', "Blitzsport")
    AddTextEntry('cii_voss_2_v', "Blitzsport Accents")
    AddTextEntry('cii_voss_3', "Carbon Rush")
    AddTextEntry('cii_voss_3_v', "Carbon Rush Accents")
    AddTextEntry('cii_wat_1', "Valentine Special")
    AddTextEntry('cii_wat_1_v', "Valentine Special Accents")
    AddTextEntry('cii_wat_2', "With Love")
    AddTextEntry('cii_wat_2_v', "With Love Accents")
    AddTextEntry('cii_wat_3', "Pandastic")
    AddTextEntry('cii_wat_3_v', "Pandastic Accents")
    AddTextEntry('cii_nis', "Tornado ZR")
    AddTextEntry('cii_nis_v', "Tornado ZR Accents")
    AddTextEntry('cii_lom', "Inferno R")
    AddTextEntry('cii_lom_v', "Inferno R Accents")
    AddTextEntry('cii_bs_1', "DriftMaster")
    AddTextEntry('cii_bs_1_v', "DriftMaster Accents")
    AddTextEntry('cii_bs_2', "Stratospeed")
    AddTextEntry('cii_bs_2_v', "Stratospeed Accents")
    AddTextEntry('cii_bs_3', "Delta V8")
    AddTextEntry('cii_bs_3_v', "Delta V8 Accents")
    AddTextEntry('cii_bs_4', "Zenith RS")
    AddTextEntry('cii_bs_4_v', "Zenith RS Accents")
    AddTextEntry('cii_bs_5', "Club Evo")
    AddTextEntry('cii_bs_5_v', "Club Evo Accents")
    AddTextEntry('cii_cos_1', "Turbochrome")
    AddTextEntry('cii_cos_1_v', "Turbochrome Accents")
    AddTextEntry('cii_cos_2', "Eclipse X5")
    AddTextEntry('cii_cos_2_v', "Eclipse X5 Accents")
    AddTextEntry('cii_cos_3', "Nova Speed")
    AddTextEntry('cii_cos_3_v', "Nova Speed Accents")
    AddTextEntry('cii_cos_4', "Blade V10")
    AddTextEntry('cii_cos_4_v', "Blade V10 Accents")
    AddTextEntry('cii_cos_5', "Quantum RS")
    AddTextEntry('cii_cos_5_v', "Quantum RS Accents")
    AddTextEntry('cii_wor_1', "Raptor ZX")
    AddTextEntry('cii_wor_1_v', "Raptor ZX Accents")
    AddTextEntry('cii_wor_2', "Fusion Five")
    AddTextEntry('cii_wor_2_v', "Fusion Five Accents")
    AddTextEntry('cii_wor_3', "Cheetah X")
    AddTextEntry('cii_wor_3_v', "Cheetah X Accents")
    AddTextEntry('cii_wor_4', "Tempest X1")
    AddTextEntry('cii_wor_4_v', "Tempest X1 Accents")
    AddTextEntry('cii_wor_5', "Apex Flare")
    AddTextEntry('cii_wor_5_v', "Apex Flare Accents")
    AddTextEntry('cii_wor_6', "Nitro Surge")
    AddTextEntry('cii_wor_6_v', "Nitro Surge Accents")
    AddTextEntry('cii_wor_7', "Zephyr X5")
    AddTextEntry('cii_wor_7_v', "Zephyr X5 Accents")
    AddTextEntry('cii_wor_8', "Chrono Speed")
    AddTextEntry('cii_wor_8_v', "Chrono Speed Accents")
    AddTextEntry('cii_wor_9', "Fury RS")
    AddTextEntry('cii_wor_9_v', "Fury RS Accents")
    AddTextEntry('cii_wor_10', "Hyperblade")
    AddTextEntry('cii_wor_10_v', "Hyperblade Accents")
    AddTextEntry('cii_wor_11', "Formula Z")
    AddTextEntry('cii_wor_11_v', "Formula Z Accents")
    AddTextEntry('cii_3d_1', "Alpha GT")
    AddTextEntry('cii_3d_1_v', "Alpha GT Accents")
    AddTextEntry('cii_3d_2', "Razor Veloce")
    AddTextEntry('cii_3d_2_v', "Razor Veloce Accents")
    AddTextEntry('cii_3d_3', "Nova XT")
    AddTextEntry('cii_3d_3_v', "Nova XT Accents")
    AddTextEntry('cii_3d_4', "Pulsar Z")
    AddTextEntry('cii_3d_4_v', "Pulsar Z Accents")
    AddTextEntry('cii_3d_5', "Pulsar A")
    AddTextEntry('cii_3d_5_v', "Pulsar A Accents")
    AddTextEntry('cii_3d_6', "Thunder Z")
    AddTextEntry('cii_3d_6_v', "Thunder Z Accents")
    AddTextEntry('cii_3d_7', "Turbo Flux")
    AddTextEntry('cii_3d_7_v', "Turbo Flux Accents")
    AddTextEntry('cii_3d_8', "Dashspeed X")
    AddTextEntry('cii_3d_8_v', "Dashspeed X Accents")
    AddTextEntry('cii_3d_9', "Dashspeed Y")
    AddTextEntry('cii_3d_9_v', "Dashspeed Y Accents")
    AddTextEntry('cii_3d_10', "Apexforce X")
    AddTextEntry('cii_3d_10_v', "Apexforce X Accents")
    AddTextEntry('cii_3d_11', "Apexforce Y")
    AddTextEntry('cii_3d_11_v', "Apexforce Y Accents")
    AddTextEntry('cii_ffs_1', "Eclipse GT")
    AddTextEntry('cii_ffs_1_v', "Eclipse GT Accents")
    AddTextEntry('cii_ffs_2', "Hyperdrive")
    AddTextEntry('cii_ffs_2_v', "Hyperdrive Accents")
    AddTextEntry('cii_ffs_3', "Circuit X")
    AddTextEntry('cii_ffs_3_v', "Circuit X Accents")
    AddTextEntry('cii_ffs_4', "Falcon GT")
    AddTextEntry('cii_ffs_4_v', "Falcon GT Accents")
    AddTextEntry('cii_ffs_5', "Blitz X5")
    AddTextEntry('cii_ffs_5_v', "Blitz X5 Accents")
    AddTextEntry('cii_ffs_6', "Nitroglide")
    AddTextEntry('cii_ffs_6_v', "Nitroglide Accents")
    AddTextEntry('cii_ffs_7', "Velocity V12")
    AddTextEntry('cii_ffs_7_v', "Velocity V12 Accents")
    AddTextEntry('cii_ffs_8', "Striker Z")
    AddTextEntry('cii_ffs_8_v', "Striker Z Accents")
    AddTextEntry('cii_ffs_9', "Vector Sport")
    AddTextEntry('cii_ffs_9_v', "Vector Sport Accents")
    AddTextEntry('cii_ffs_10', "Stormbreaker")
    AddTextEntry('cii_ffs_10_v', "Stormbreaker Accents")
    AddTextEntry('cii_ffs_11', "Pulsar RS")
    AddTextEntry('cii_ffs_11_v', "Pulsar RS Accents")
    AddTextEntry('cii_ffs_12', "Zenith XR")
    AddTextEntry('cii_ffs_12_v', "Zenith XR Accents")
    AddTextEntry('cii_ffs_13', "Drift Star")
    AddTextEntry('cii_ffs_13_v', "Drift Star Accents")
    AddTextEntry('cii_ffs_14', "Comet LX")
    AddTextEntry('cii_ffs_14_v', "Comet LX Accents")
    AddTextEntry('cii_ffs_15', "Fury XT")
    AddTextEntry('cii_ffs_15_v', "Fury XT Accents")
    AddTextEntry('cii_ffs_16', "Razorback Z")
    AddTextEntry('cii_ffs_16_v', "Razorback Z Accents")
    AddTextEntry('cii_ffs_17', "Hyperchrome")
    AddTextEntry('cii_ffs_17_v', "Hyperchrome Accents")
    AddTextEntry('cii_ffs_18', "Helix RS")
    AddTextEntry('cii_ffs_18_v', "Helix RS Accents")
    AddTextEntry('cii_ffs_19', "Nitro Edge")
    AddTextEntry('cii_ffs_19_v', "Nitro Edge Accents")
    AddTextEntry('cii_ffs_20', "Circuit Five")
    AddTextEntry('cii_ffs_20_v', "Circuit Five Accents")
    AddTextEntry('cii_ffs_21', "Sonicwave")
    AddTextEntry('cii_ffs_21_v', "Sonicwave Accents")
    AddTextEntry('cii_ffs_22', "Apex Sonic")
    AddTextEntry('cii_ffs_22_v', "Apex Sonic Accents")
    AddTextEntry('cii_ffs_23', "Phantom Drift")
    AddTextEntry('cii_ffs_23_v', "Phantom Drift Accents")
    AddTextEntry('cii_vor_1', "Venom RS")
    AddTextEntry('cii_vor_1_v', "Venom RS Accents")
    AddTextEntry('cii_vor_2', "Carbon XT")
    AddTextEntry('cii_vor_2_v', "Carbon XT Accents")
    AddTextEntry('cii_vor_3', "Tornado Pro")
    AddTextEntry('cii_vor_3_v', "Tornado Pro Accents")
    AddTextEntry('cii_vor_4', "Driftfire")
    AddTextEntry('cii_vor_4_v', "Driftfire Accents")
    AddTextEntry('cii_vor_5', "Thunder V")
    AddTextEntry('cii_vor_5_v', "Thunder V Accents")
    AddTextEntry('cii_vor_6', "Zenith Vortex")
    AddTextEntry('cii_vor_6_v', "Zenith Vortex Accents")
    AddTextEntry('cii_vor_7', "Blade XR")
    AddTextEntry('cii_vor_7_v', "Blade XR Accents")
    AddTextEntry('cii_vor_8', "Nitro Torque")
    AddTextEntry('cii_vor_8_v', "Nitro Torque Accents")
    AddTextEntry('cii_vor_9', "Flux ZR")
    AddTextEntry('cii_vor_9_v', "Flux ZR Accents")
    AddTextEntry('cii_vor_10', "Phantom V10")
    AddTextEntry('cii_vor_10_v', "Phantom V10 Accents")
    AddTextEntry('cii_rt_1', "Apex Nova")
    AddTextEntry('cii_rt_1_v', "Apex Nova Accents")
    AddTextEntry('cii_rt_2', "Cyclone XT")
    AddTextEntry('cii_rt_2_v', "Cyclone XT Accents")
    AddTextEntry('cii_rt_3', "Velocity LX")
    AddTextEntry('cii_rt_3_v', "Velocity LX Accents")
    AddTextEntry('cii_sry_1', "Turbo Boost")
    AddTextEntry('cii_sry_1_v', "Turbo Boost Accents")
    AddTextEntry('cii_sry_2', "Inferno Vortex")
    AddTextEntry('cii_sry_2_v', "Inferno Vortex Accents")
    AddTextEntry('cii_sry_3', "Striker Evo")
    AddTextEntry('cii_sry_3_v', "Striker Evo Accents")
    AddTextEntry('cii_sry_4', "Nova Drift")
    AddTextEntry('cii_sry_4_v', "Nova Drift Accents")
    AddTextEntry('cii_sry_5', "Raptor Five")
    AddTextEntry('cii_sry_5_v', "Raptor Five Accents")
    AddTextEntry('cii_sry_6', "Zenith Pro X")
    AddTextEntry('cii_sry_6_v', "Zenith Pro X Accents")
    AddTextEntry('cii_sry_7', "Zenith Pro Y")
    AddTextEntry('cii_sry_7_v', "Zenith Pro Y Accents")
    AddTextEntry('cii_sry_8', "Hyper Nova")
    AddTextEntry('cii_sry_8_v', "Hyper Nova Accents")
    AddTextEntry('cii_hr_1', "Turbo Fusion")
    AddTextEntry('cii_hr_1_v', "Turbo Fusion Accents")
    AddTextEntry('cii_hr_2', "Razor Drift")
    AddTextEntry('cii_hr_2_v', "Razor Drift Accents")
    AddTextEntry('cii_hr_3', "Chrono X")
    AddTextEntry('cii_hr_3_v', "Chrono X Accents")
    AddTextEntry('cii_hr_4', "Quantum Evo")
    AddTextEntry('cii_hr_4_v', "Quantum Evo Accents")
    AddTextEntry('cii_hr_5', "Apexforce V8")
    AddTextEntry('cii_hr_5_v', "Apexforce V8 Accents")
    AddTextEntry('cii_hr_6', "Striker Veloce")
    AddTextEntry('cii_hr_6_v', "Striker Veloce Accents")
    AddTextEntry('cii_hr_7', "Nitrochrome")
    AddTextEntry('cii_hr_7_v', "Nitrochrome Accents")
    AddTextEntry('cii_hr_8', "Tornado Fusion")
    AddTextEntry('cii_hr_8_v', "Tornado Fusion Accents")
    AddTextEntry('cii_hr_9', "Eclipse RS")
    AddTextEntry('cii_hr_9_v', "Eclipse RS Accents")
    AddTextEntry('cii_hr_10', "Velocity Evo")
    AddTextEntry('cii_hr_10_v', "Velocity Evo Accents")
end)